# Generated by Django 5.1.15 on 2026-08-22 15:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='chat.chatsession')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModelResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_id', models.CharField(help_text="Registry id, e.g. 'gpt-4o-mini'", max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, default='', help_text='Vendor-side model identifier actually called.', max_length=150)),
                ('response_text', models.TextField(blank=True, default='')),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='chat.chatturn')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('turn', 'model_id'), name='unique_turn_model_response')],
            },
        ),
    ]
