# Generated by Django 5.1.15 on 2026-08-22 12:38

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_vector', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('preference_updated_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_tags', models.ManyToManyField(blank=True, related_name='onboarded_users', to='catalog.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
