# Generated by Django 5.1.15 on 2026-08-22 12:38

import django.db.models.deletion
import django.db.models.functions.text
import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Makes the migration self-contained on any Postgres 15+ install:
        # CREATE EXTENSION IF NOT EXISTS vector; (requires superuser or
        # a role with CREATE privileges on the database).
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('pricing_tier', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid')], default='freemium', max_length=12)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='384-dim sentence embedding of name + description + tags (generated offline, never on the request path).', null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tools', to='catalog.tag')),
            ],
            options={
                'ordering': ('-avg_rating', '-created_at'),
                'indexes': [models.Index(fields=['category'], name='catalog_too_categor_6e8fda_idx'), models.Index(fields=['pricing_tier'], name='catalog_too_pricing_958bac_idx'), pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='tool_embedding_ivfflat', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
