# Generated by Django 5.1.15 on 2026-08-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tool',
            name='tool_embedding_ivfflat',
        ),
    ]
