# Generated by Django 5.1.15 on 2026-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_tool_tool_embedding_ivfflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='checked_title',
            field=models.CharField(blank=True, help_text='<title> of the target page at last check (staleness signal).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_live',
            field=models.BooleanField(default=True, help_text="Last known state of the tool's public URL."),
        ),
        migrations.AddField(
            model_name='tool',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Set after 3+ consecutive failed checks — a human decides, never auto-delete (crawl errors are often transient outages).'),
        ),
    ]
