"""
Seed dataset for the demo catalog.

Two sources:
  * REAL_TOOLS  — ~100 curated, real-world AI tools (name/category/pricing/
                 tags/description) for a credible demo.
  * generator   — deterministic synthetic tools to reach any target count
                 (seeded RNG, so `seed_tools` is idempotent-ish and stable).

Descriptions double as embedding input, so they are written to be genuinely
distinguishable between tools.
"""

CATEGORIES: list[tuple[str, str]] = [
    ("Writing", "AI assistants for drafting, editing and polishing text — copywriting, blog posts, documentation."),
    ("Image Generation", "Text-to-image models and editors for art, product shots, avatars and illustrations."),
    ("Video & Audio", "Generative video, voice synthesis, music, dubbing and podcast tooling."),
    ("Code & Development", "Coding copilots, code review, test generation and developer productivity AI."),
    ("Chatbots & Assistants", "General-purpose conversational assistants and agents."),
    ("Productivity", "Meeting notes, task automation, knowledge search and personal organisation."),
    ("Data & Analytics", "SQL copilots, dashboards, forecasting and spreadsheet AI."),
    ("Marketing & SEO", "Ad copy, SEO content briefs, social scheduling and campaign analytics."),
    ("Design & UI", "UI generation, brand kits, prototyping and creative asset tooling."),
    ("Research & Education", "Literature search, summarisation, tutoring and study assistants."),
]

TAGS: list[str] = [
    "api", "browser-extension", "chrome-extension", "cli", "collaboration",
    "code-generation", "copywriting", "customer-support", "data-visualization",
    "developer-tools", "document-editing", "e-commerce", "education",
    "email", "english", "free-tier", "git", "grammar", "image-editing",
    "integration", "logo", "long-form", "marketing", "multilingual",
    "no-code", "note-taking", "open-source", "personalization",
    "presentation", "prompt-library", "real-time", "research", "resume",
    "seo", "speech-to-text", "spreadsheets", "summarization", "team-plan",
    "text-to-speech", "transcription", "translation", "video-editing",
    "voice-cloning", "webinars", "workflow-automation", "writing-assistant",
]

# (name, category, pricing, [tags], description)
REAL_TOOLS: list[tuple[str, str, str, list[str], str]] = [
    ("ChatGPT", "Chatbots & Assistants", "freemium", ["api", "multilingual", "real-time", "collaboration"],
     "OpenAI's conversational assistant for answering questions, drafting documents, brainstorming ideas, analyzing text and writing code across dozens of languages."),
    ("Claude", "Chatbots & Assistants", "freemium", ["api", "long-form", "document-editing", "summarization"],
     "Anthropic's AI assistant known for careful reasoning, long-context document analysis, nuanced writing and safe, steerable behavior for professional work."),
    ("Gemini", "Chatbots & Assistants", "freemium", ["api", "multilingual", "real-time", "integration"],
     "Google's multimodal assistant that reasons across text, images and code, integrated with Search and Workspace for research-backed answers."),
    ("Perplexity", "Research & Education", "freemium", ["research", "real-time", "summarization", "api"],
     "AI-powered answer engine that searches the live web, cites its sources and synthesizes concise, referenced summaries for any question."),
    ("Jasper", "Marketing & SEO", "paid", ["copywriting", "marketing", "brand-voice", "team-plan"],
     "Marketing-focused writing platform generating on-brand blog posts, ads and email campaigns with templates and brand-voice controls."),
    ("Copy.ai", "Marketing & SEO", "freemium", ["copywriting", "marketing", "email", "workflow-automation"],
     "AI copywriting tool with playbooks for sales outreach, product descriptions and ad variants, built around a go-to-market workflow engine."),
    ("Writesonic", "Writing", "freemium", ["copywriting", "seo", "long-form", "marketing"],
     "AI writer focused on SEO articles and ad copy, with a fact-checking layer and bulk generation for content teams."),
    ("Grammarly", "Writing", "freemium", ["grammar", "browser-extension", "writing-assistant", "team-plan"],
     "Writing assistant that checks grammar, clarity, tone and plagiarism across apps, with generative rewriting and enterprise style guides."),
    ("QuillBot", "Writing", "freemium", ["grammar", "paraphrasing", "summarization", "browser-extension"],
     "Paraphrasing and summarization suite for students and professionals, with citation tools and a flow-optimized thesaurus."),
    ("Wordtune", "Writing", "freemium", ["grammar", "writing-assistant", "browser-extension", "personalization"],
     "Sentence-level rewriting assistant offering casual and formal tones to sharpen and shorten any paragraph."),
    ("Notion AI", "Productivity", "freemium", ["note-taking", "summarization", "collaboration", "writing-assistant"],
     "Q&A, drafting and autofill features woven into Notion pages and databases, summarizing meeting notes and docs where you work."),
    ("Mem", "Productivity", "freemium", ["note-taking", "personalization", "api"],
     "AI-native note repository that organizes and resurfaces notes automatically using semantic search instead of folders."),
    ("Otter.ai", "Productivity", "freemium", ["transcription", "meeting-notes", "collaboration", "real-time"],
     "Real-time meeting transcription with speaker identification, summaries and action items synced to Zoom, Meet and Teams."),
    ("Fireflies.ai", "Productivity", "freemium", ["transcription", "meeting-notes", "workflow-automation", "team-plan"],
     "Meeting recorder and conversation-intelligence platform that searches transcripts, scores talk time and pushes notes to CRMs."),
    ("Fathom", "Productivity", "freemium", ["transcription", "meeting-notes", "summarization"],
     "Free AI notetaker that records, transcribes and highlights sales calls, generating CRM-ready summaries instantly after each meeting."),
    ("Rewind", "Productivity", "paid", ["personalization", "real-time", "macOS"],
     "Personal memory assistant that indexes everything you've seen and said on your device for searchable recall of past work."),
    ("GitHub Copilot", "Code & Development", "paid", ["code-generation", "developer-tools", "ide-plugin", "git"],
     "Inline code completion and chat for VS Code and JetBrains, translating comments and intentions into whole functions across dozens of languages."),
    ("Cursor", "Code & Development", "freemium", ["code-generation", "developer-tools", "ide-plugin", "codebase-context"],
     "AI-first code editor built around a chat that understands your whole repository, enabling multi-file edits and terminal command suggestions."),
    ("Tabnine", "Code & Development", "freemium", ["code-generation", "developer-tools", "privacy", "self-hosted"],
     "Code completion hub with private deployment options, learning team code conventions while keeping source on your infrastructure."),
    ("Codeium", "Code & Development", "free", ["code-generation", "developer-tools", "ide-plugin", "free-tier"],
     "Free AI code completion and chat for 70+ languages with unlimited individual usage and context-aware refactoring."),
    ("Sourcegraph Cody", "Code & Development", "freemium", ["code-generation", "codebase-context", "developer-tools", "open-source"],
     "Coding assistant with deep codebase context and retrieval, answering architectural questions and generating patches across monorepos."),
    ("Snyk", "Code & Development", "freemium", ["security", "developer-tools", "code-review", "open-source"],
     "Developer security platform that finds and auto-fixes vulnerabilities in dependencies, containers and infrastructure-as-code."),
    ("Sweep AI", "Code & Development", "freemium", ["code-generation", "git", "developer-tools", "bug-fixing"],
     "AI junior developer that turns GitHub issues into reviewed pull requests, writing tests and fixing CI failures autonomously."),
    ("Datadog Bits AI", "Data & Analytics", "paid", ["observability", "developer-tools", "incident-management"],
     "AI assistant for cloud observability that investigates alerts, correlates signals and drafts incident timelines from telemetry."),
    ("Hex", "Data & Analytics", "freemium", ["notebooks", "sql", "data-visualization", "collaboration"],
     "Collaborative data notebook with an AI copilot for SQL and Python, turning queries into shareable interactive reports."),
    ("Julius AI", "Data & Analytics", "freemium", ["data-visualization", "spreadsheets", "analysis"],
     "Conversational data analyst: upload spreadsheets and get charts, regressions and forecasts through plain-English chat."),
    ("Rows", "Data & Analytics", "freemium", ["spreadsheets", "api", "data-visualization", "integration"],
     "Spreadsheet with AI analysis functions and live data integrations for growth and finance teams."),
    ("Text2SQL.ai", "Data & Analytics", "freemium", ["sql", "code-generation", "developer-tools"],
     "Converts natural-language questions into optimized SQL queries for your schema, with dialect-aware tuning."),
    ("Polymer", "Data & Analytics", "freemium", ["data-visualization", "spreadsheets", "no-code"],
     "No-code dashboard builder that ingests spreadsheets and auto-generates insights and visualizations."),
    ("Metabase", "Data & Analytics", "free", ["data-visualization", "open-source", "sql", "self-hosted"],
     "Open-source BI tool where anyone can ask questions of company data with a friendly query builder or SQL."),
    ("Midjourney", "Image Generation", "paid", ["text-to-image", "art", "stylization", "community"],
     "Industry-leading text-to-image model famed for painterly, cinematic renders, steered through Discord and a web editor with style references."),
    ("DALL·E 3", "Image Generation", "freemium", ["text-to-image", "api", "image-editing", "integration"],
     "OpenAI's image generator with precise prompt adherence, accessible through ChatGPT and a developer API with editing endpoints."),
    ("Stable Diffusion", "Image Generation", "free", ["text-to-image", "open-source", "self-hosted", "image-editing"],
     "Open-source latent-diffusion image model with a huge ecosystem of fine-tunes, ControlNets and local interfaces."),
    ("Ideogram", "Image Generation", "freemium", ["text-to-image", "typography", "logo", "art"],
     "Text-to-image model specializing in legible typography and poster design, ideal for logos and graphic layouts."),
    ("Leonardo.Ai", "Image Generation", "freemium", ["text-to-image", "game-assets", "image-editing", "api"],
     "Production image platform with fine-tuned models, canvas editing and asset pipelines for game studios."),
    ("Playground AI", "Image Generation", "freemium", ["text-to-image", "image-editing", "graphic-design"],
     "Browser-based image editor combining generation, inpainting and templates for marketing graphics."),
    ("Remove.bg", "Image Generation", "freemium", ["image-editing", "background-removal", "api", "e-commerce"],
     "One-click background removal for photos and video with pixel-precise edges, available via web and API."),
    ("Magnific AI", "Image Generation", "paid", ["upscaling", "image-editing", "art"],
     "AI upscaler that reimagines detail at extreme resolutions, turning low-res renders into gallery-grade images."),
    ("Krea", "Image Generation", "freemium", ["text-to-image", "real-time", "image-editing"],
     "Real-time generation canvas where sketches and prompts render instantly with style controls."),
    ("Runway", "Video & Audio", "freemium", ["text-to-video", "video-editing", "api"],
     "Generative video suite powering text-to-video, inpainting and motion brush tools used in film production."),
    ("Pika", "Video & Audio", "freemium", ["text-to-video", "animation", "video-editing"],
     "Playful text-to-video platform for animating ideas, products and memes with camera controls."),
    ("Luma Dream Machine", "Video & Audio", "freemium", ["text-to-video", "3d", "animation"],
     "Photorealistic video generation from text and images with coherent motion, from the creators of NeRF capture."),
    ("Descript", "Video & Audio", "freemium", ["video-editing", "transcription", "podcasting", "overdub"],
     "Edit video and podcasts by editing the transcript, with studio-grade voice cloning and filler-word removal."),
    ("ElevenLabs", "Video & Audio", "freemium", ["text-to-speech", "voice-cloning", "multilingual", "api"],
     "Realistic text-to-speech and voice cloning in 30+ languages, with dubbing and audio-native chat APIs."),
    ("Murf AI", "Video & Audio", "freemium", ["text-to-speech", "voiceover", "e-learning"],
     "Studio for studio-quality voiceovers with pitch, pause and emphasis controls across 120 voices."),
    ("Suno", "Video & Audio", "freemium", ["music-generation", "songwriting", "api"],
     "Turns text prompts into full songs with vocals and instrumentation across genres."),
    ("AIVA", "Video & Audio", "freemium", ["music-generation", "soundtrack", "composition"],
     "AI composer specializing in orchestral and cinematic soundtracks with editable MIDI scores."),
    ("Krisp", "Video & Audio", "freemium", ["noise-cancellation", "transcription", "meeting-notes"],
     "AI noise cancellation and accent conversion for calls, with meeting transcription layered on top."),
    ("Whisper API", "Video & Audio", "paid", ["speech-to-text", "transcription", "api", "multilingual"],
     "OpenAI's speech recognition endpoint delivering accurate multilingual transcription and translation."),
    ("Adobe Firefly", "Design & UI", "freemium", ["text-to-image", "image-editing", "graphic-design", "commercial-safe"],
     "Adobe's commercially-safe generative models embedded across Photoshop, Illustrator and Express for creative pros."),
    ("Figma AI", "Design & UI", "freemium", ["ui-design", "prototyping", "collaboration", "code-generation"],
     "Design generation inside Figma: instant layouts from prompts, automatic prototype wiring and copy suggestions."),
    ("Uizard", "Design & UI", "freemium", ["ui-design", "prototyping", "no-code", "wireframing"],
     "Turns hand-drawn sketches and prompts into editable multi-platform app designs."),
    ("Galileo AI", "Design & UI", "paid", ["ui-design", "prototyping", "text-to-ui"],
     "Text-prompt to high-fidelity UI generation for mobile and web interfaces with editable components."),
    ("Looka", "Design & UI", "paid", ["logo", "branding", "no-code"],
     "AI logo maker that builds a complete brand kit — colors, fonts, business cards — from a short brief."),
    ("Canva Magic Studio", "Design & UI", "freemium", ["graphic-design", "text-to-image", "presentation", "brand-voice"],
     "Canva's AI suite: Magic Write, Magic Design, background remover and brand-locked templates for teams."),
    ("Beautiful.ai", "Design & UI", "freemium", ["presentation", "storytelling", "templates"],
     "Presentation tool with smart slides that auto-arrange content as you add it."),
    ("Tome", "Design & UI", "freemium", ["presentation", "storytelling", "image-generation"],
     "Generative storytelling app that assembles narrative decks with text, images and data from one prompt."),
    ("Intercom Fin", "Chatbots & Assistants", "paid", ["customer-support", "resolution", "integration"],
     "Support agent that resolves customer conversations autonomously using your help-center content with accurate answers or escalation."),
    ("Ada", "Chatbots & Assistants", "paid", ["customer-support", "no-code", "integration", "multilingual"],
     "No-code AI customer service platform resolving inquiries across chat, email and voice in 100+ languages."),
    ("Kommunicate", "Chatbots & Assistants", "freemium", ["customer-support", "live-chat", "no-code"],
     "Chatbot builder combining GPT-powered answers with human handoff for websites and apps."),
    ("Chatbase", "Chatbots & Assistants", "freemium", ["customer-support", "rag", "api", "integration"],
     "Upload documents or link a site and get a custom chatbot grounded in that content, embeddable anywhere."),
    ("Zapier AI", "Marketing & SEO", "freemium", ["workflow-automation", "integration", "no-code", "api"],
     "AI actions and chatbots inside Zapier automations connecting 6,000+ apps with natural-language Zap building."),
    ("Surfer SEO", "Marketing & SEO", "paid", ["seo", "content-briefs", "keyword-research", "writing-assistant"],
     "On-page SEO editor that scores content against live search results and briefs writers on structure and entities."),
    ("Frase", "Marketing & SEO", "freemium", ["seo", "content-briefs", "keyword-research"],
     "SEO content tool that researches, briefs, writes and optimizes articles against the current SERP."),
    ("Clearscope", "Marketing & SEO", "paid", ["seo", "content-optimization", "integration"],
     "Content optimization reports grading readability and keyword coverage for editorial teams."),
    ("SE Ranking AI Writer", "Marketing & SEO", "freemium", ["seo", "copywriting", "keyword-research"],
     "SEO platform with an AI writer that drafts search-optimized articles from tracked keyword clusters."),
    ("AdCreative.ai", "Marketing & SEO", "paid", ["ad-copy", "creative-optimization", "e-commerce", "image-generation"],
     "Generates conversion-scored ad creatives and copy variants for paid social and search campaigns."),
    ("Pencil", "Marketing & SEO", "paid", ["ad-copy", "creative-optimization", "video-editing"],
     "Generative ad platform producing and testing branded video and image ads with predicted performance."),
    ("Apollo AI", "Marketing & SEO", "freemium", ["sales-intelligence", "email", "workflow-automation"],
     "Sales intelligence and engagement suite with AI prospecting, email sequencing and call insights."),
    ("HyperWrite", "Writing", "freemium", ["writing-assistant", "personalization", "browser-extension"],
     "Everyday AI writing companion with autowrite, email replies and a personal style model."),
    ("Rytr", "Writing", "freemium", ["copywriting", "templates", "multilingual"],
     "Lightweight AI writer with 40+ use-case templates and tone controls in 30 languages."),
    ("Anyword", "Writing", "freemium", ["copywriting", "marketing", "predictive-scoring"],
     "Copywriting platform scoring every generated variant's expected conversion before you publish."),
    ("Sudowrite", "Writing", "paid", ["fiction", "long-form", "brainstorming", "writing-assistant"],
     "Creative-writing studio for novelists: describe, rewrite and expand scenes while preserving author voice."),
    ("NovelAI", "Writing", "paid", ["fiction", "long-form", "image-generation", "privacy"],
     "Subscription storytelling sandbox with finetuned narrative models and anime-style image generation."),
    ("DeepL Write", "Writing", "free", ["translation", "grammar", "multilingual", "tone"],
     "AI writing improver tuned for precise, natural phrasing in English and German with tone selection."),
    ("Elicit", "Research & Education", "freemium", ["research", "papers", "summarization", "data-extraction"],
     "AI research assistant that finds relevant papers, extracts findings into tables and drafts literature reviews."),
    ("Consensus", "Research & Education", "freemium", ["research", "papers", "evidence-synthesis"],
     "Search engine that answers yes/no scientific questions by aggregating claims from peer-reviewed papers."),
    ("Semantic Scholar", "Research & Education", "free", ["research", "papers", "citations", "api"],
     "AI-enhanced academic index with influential-citation rankings and paper recommendation feeds."),
    ("Scite AI", "Research & Education", "paid", ["research", "citations", "papers"],
     "Smart citations showing whether each paper supports or contradicts a claim, with reference checks."),
    ("SciSpace", "Research & Education", "freemium", ["papers", "summarization", "citation-generator"],
     "Reader for PDFs that explains math and jargon in place and generates literature tables."),
    ("Khanmigo", "Research & Education", "free", ["tutoring", "education", "socratic"],
     "Khan Academy's Socratic AI tutor guiding K-12 and college learners step by step through problems."),
    ("Quizlet Q-Chat", "Research & Education", "freemium", ["tutoring", "flashcards", "education"],
     "Conversational study tutor building adaptive flashcards and quizzes from any material."),
    ("Duolingo Max", "Research & Education", "freemium", ["language-learning", "conversation", "education"],
     "GPT-4 powered role-play conversations and explain-my-answer features inside Duolingo courses."),
    ("Photomath", "Research & Education", "free", ["math", "mobile-app", "education"],
     "Scan a handwritten equation for step-by-step solutions and interactive graphs."),
    ("Gamma", "Productivity", "freemium", ["presentation", "no-code", "web-publishing"],
     "Prompt-to-deck generator creating polished, interactive presentations and documents that publish as web pages."),
    ("Reclaim AI", "Productivity", "freemium", ["scheduling", "calendar", "workflow-automation"],
     "Smart calendar assistant that auto-schedules tasks, habits and meetings around your priorities."),
    ("Motion", "Productivity", "paid", ["project-management", "scheduling", "team-plan"],
     "AI project manager blending tasks, calendar and deadlines into one continuously replanned day."),
    ("Clockwise", "Productivity", "freemium", ["scheduling", "calendar", "team-plan"],
     "Optimizes team calendars by creating focus time and resolving meeting conflicts automatically."),
    ("Superhuman AI", "Productivity", "paid", ["email", "personalization", "speed"],
     "Email client that drafts replies in your voice, triages importance and clusters threads."),
    ("Shortwave", "Productivity", "freemium", ["email", "summarization", "search"],
     "AI inbox that summarizes threads, pinpoints action items and searches mail semantically."),
    ("SaneBox", "Productivity", "freemium", ["email", "filtering", "workflow-automation"],
     "Email triage layer training itself on your behavior to keep the inbox down to what matters."),
    ("Todoist AI Assistant", "Productivity", "freemium", ["task-management", "planning", "natural-language"],
     "Turns vague goals into planned, scheduled tasks inside the classic Todoist list manager."),
    ("Trello AI", "Productivity", "freemium", ["project-management", "no-code", "brainstorming"],
     "Board automation that generates checklists, summarizes cards and suggests next steps."),
    ("Slidesgo AI", "Design & UI", "freemium", ["presentation", "templates", "education"],
     "Presentation template library with AI deck generation from topic and tone prompts."),
    ("Beautifullyted", "Design & UI", "paid", ["branding", "typography"],
     "Boutique AI typography studio matching brand fonts and pairing systems."),
    ("Picsart AI", "Image Generation", "freemium", ["image-editing", "mobile-app", "graphic-design"],
     "Creative ecosystem with AI photo tools, backgrounds, stickers and quick logo makers on mobile."),
    ("Canva Text-to-Image", "Image Generation", "free", ["text-to-image", "graphic-design", "free-tier"],
     "Prompt-based image generation inside Canva docs and designs."),
    ("Craiyon", "Image Generation", "free", ["text-to-image", "free-tier", "fun"],
     "Free lightweight image generator for quick concept sketches and memes."),
    ("Bing Image Creator", "Image Generation", "free", ["text-to-image", "free-tier", "integration"],
     "Microsoft's DALL·E-powered generator embedded in Bing search and Designer."),
    ("NightCafe", "Image Generation", "freemium", ["text-to-image", "community", "art", "styles"],
     "Aggregator studio for multiple open models with daily challenges and a big art community."),
    ("Lexica", "Image Generation", "freemium", ["text-to-image", "prompt-library", "art"],
     "Stable Diffusion search engine and generator with a vast prompt-art reference library."),
    ("Clipdrop", "Image Generation", "freemium", ["image-editing", "api", "cleanup", "relight"],
     "Toolkit of AI photo utilities — cleanup, relight, upscale, reimagine — with solid APIs."),
    ("Photoroom", "Image Generation", "freemium", ["background-removal", "e-commerce", "mobile-app"],
     "Product photography studio creating studio-grade e-commerce shots from phone photos."),
    ("Vizcom", "Design & UI", "freemium", ["industrial-design", "sketching", "rendering"],
     "Sketch-to-render tool for industrial designers turning line work into shaded concept renders."),
    ("Kittl", "Design & UI", "freemium", ["graphic-design", "typography", "templates", "print-on-demand"],
     "Design platform with AI vector generation and ornate typography for merchandise and branding."),
    ("Lookr.fyi", "Design & UI", "freemium", ["moodboards", "inspiration"],
     "AI moodboard generator assembling palettes and references for creative direction."),
    ("Miro AI", "Productivity", "freemium", ["whiteboarding", "brainstorming", "summarization", "collaboration"],
     "Generative helpers on the Miro board: clusters, summaries, images and user-story synthesis."),
    ("Whimsical AI", "Productivity", "freemium", ["flowcharts", "brainstorming", "mind-maps"],
     "One-click mind-map and flowchart expansion from a seed idea."),
    ("Airtable AI", "Productivity", "freemium", ["database", "no-code", "workflow-automation", "categorization"],
     "AI fields that summarize, categorize and translate records inside Airtable bases."),
    ("Notion Calendar", "Productivity", "free", ["calendar", "scheduling", "integration"],
     "Chronological twin of your docs connecting meeting prep notes to time blocks."),
    ("Raycast AI", "Productivity", "freemium", ["launcher", "macOS", "api", "developer-tools"],
     "Mac launcher with inline AI chat, quick AI commands and custom extensions."),
    ("LangChain", "Code & Development", "free", ["framework", "open-source", "llm-apps", "python"],
     "Framework for building LLM applications: chains, agents, retrieval and tool orchestration in Python and JS."),
    ("LlamaIndex", "Code & Development", "free", ["framework", "rag", "open-source", "python"],
     "Data framework for retrieval-augmented generation over private data with indexes and query engines."),
    ("Hugging Face", "Code & Development", "freemium", ["model-hub", "open-source", "datasets", "api"],
     "The hub for open models and datasets, with inference endpoints and transformers tooling."),
    ("v0 by Vercel", "Code & Development", "freemium", ["ui-generation", "react", "shadcn", "code-generation"],
     "Generative UI copilot producing React/Tailwind components from screenshots and prompts."),
    ("bolt.new", "Code & Development", "freemium", ["full-stack", "code-generation", "web-container"],
     "Prompt-to-full-stack-app builder running Node in the browser with one-click deploys."),
    ("Replit AI", "Code & Development", "freemium", ["ide-plugin", "code-generation", "deployment"],
     "Cloud IDE with an AI agent that builds, runs and debugs projects end to end."),
    ("Warp AI", "Code & Development", "freemium", ["terminal", "cli", "developer-tools", "macOS"],
     "AI-native terminal explaining errors, suggesting commands and scripting workflows inline."),
    ("Aider", "Code & Development", "free", ["cli", "open-source", "git", "pair-programming"],
     "Open-source terminal pair programmer editing your repo in sync with git commits."),
    ("Mintlify", "Code & Development", "freemium", ["documentation", "code-generation", "developer-tools"],
     "Documentation generator that writes and maintains docs from your codebase with an AI assistant."),
    ("CodeT5+", "Code & Development", "free", ["open-source", "research", "code-generation"],
     "Open encoder-decoder model family for code understanding, summarization and generation."),
    ("MutableAI", "Code & Development", "freemium", ["auto-documentation", "code-generation", "developer-tools"],
     "IDE extension for proto-to-production: auto-docstrings, type annotations and test generation."),
    ("Qodo", "Code & Development", "freemium", ["test-generation", "code-review", "developer-tools"],
     "Test and code-integrity agent generating meaningful test suites from behavior analysis."),
    ("Ponicode", "Code & Development", "freemium", ["test-generation", "ide-plugin"],
     "One-click unit test generation with edge-case discovery for JavaScript and Python."),
    ("Synthesia", "Video & Audio", "paid", ["avatar-video", "training", "localization", "api"],
     "Studio for AI avatar training and explainer videos in 130+ languages from a script."),
    ("HeyGen", "Video & Audio", "freemium", ["avatar-video", "localization", "personalization"],
     "Photorealistic avatars and video translation with lip-sync for marketing at scale."),
    ("Colossyan", "Video & Audio", "freemium", ["avatar-video", "training", "education"],
     "Workplace learning videos with AI presenters from PDFs and slides."),
    ("Opus Clip", "Video & Audio", "freemium", ["video-editing", "shorts", "social-media"],
     "Turns long videos into viral short clips with auto-captions and reframing."),
    ("Veed AI", "Video & Audio", "freemium", ["video-editing", "subtitles", "translation"],
     "Online editor with auto-subtitles, eye contact correction and TTS voiceovers."),
    ("Kapwing", "Video & Audio", "freemium", ["video-editing", "collaboration", "meme-generator"],
     "Collaborative web video editor with smart cut, transcription and resize automation."),
    ("Wzrd.ai", "Video & Audio", "paid", ["music-visualization", "art"],
     "Generates immersive music visualizations from audio signals."),
    ("Audiobox", "Video & Audio", "free", ["voice-cloning", "sound-effects", "research"],
     "Meta's research model for combined voice and sound generation from text and audio prompts."),
    ("Mubert", "Video & Audio", "freemium", ["royalty-free-music", "api", "streaming"],
     "Infinite royalty-free generative soundtracks for content, apps and streams via API."),
    ("Speechmatics", "Video & Audio", "freemium", ["speech-to-text", "api", "multilingual"],
     "Enterprise speech recognition with broad language coverage and real-time streaming."),
    ("AssemblyAI", "Video & Audio", "freemium", ["speech-to-text", "api", "summarization"],
     "Speech intelligence API with transcription, chapterization, PII redaction and topic detection."),
    ("Deepgram", "Video & Audio", "freemium", ["speech-to-text", "api", "real-time"],
     "Fast, accurate STT APIs built on foundational speech models, with on-prem options."),
    ("Wisperly", "Video & Audio", "freemium", ["podcasting", "show-notes", "distribution"],
     "Podcast assistant generating show notes, chapters and clips from audio uploads."),
    ("Wondercraft", "Video & Audio", "freemium", ["podcasting", "text-to-speech", "translation"],
     "Text-to-podcast studio with realistic hosts, music beds and multilingual reruns."),
    ("Journalist AI", "Writing", "freemium", ["seo", "publishing", "auto-blogging"],
     "Generates and auto-publishes SEO articles with images and internal links to your blog."),
    ("Zetty", "Writing", "freemium", ["academic", "citation", "papers"],
     "Academic writing helper tuning structure and citations for journals."),
    ("Henchman", "Writing", "freemium", ["legal-drafting", "clause-library"],
     "Contract drafting assistant surfacing your firm's best clauses as you type."),
    ("Spellbook", "Writing", "paid", ["legal-drafting", "contract-review"],
     "Word add-in drafting and flagging issues in contracts using GPT-4."),
    ("Trinka", "Writing", "freemium", ["grammar", "academic", "technical-writing"],
     "Grammar and style checker tuned for academic and technical writing conventions."),
    ("ProWritingAid", "Writing", "freemium", ["grammar", "style-analysis", "writing-assistant"],
     "Deep writing analytics and line edits with 20+ readability and style reports."),
    ("LanguageTool", "Writing", "freemium", ["grammar", "multilingual", "browser-extension", "open-source"],
     "Open-source proofreader for 30+ languages with self-hosting options."),
]
